# Generated by Django 2.2 on 2019-05-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pictures',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
    ]
